# -*- coding: utf-8 -*-
"""Damodar_Valley_Methane_Hotspot_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a-chOvhk1BGkD_AHcEgf9qTTReIy82as

# Satellite-Based Methane Anomaly Detection over the Damodar Valley Coal Belt

### Using Sentinel-5P TROPOMI, Google Earth Engine, Python & Geemap

**Author:** Dibya Jyoti Das

---

## Objective

Develop a satellite-based workflow to detect methane emission hotspots across India's Damodar Valley Coal Belt using Sentinel-5P TROPOMI observations. Historical baseline modelling, statistical anomaly detection, and interactive geospatial visualization are used to identify persistent methane enhancements associated with major coal mining regions.

---

# 1. Install Required Libraries
"""

!pip install earthengine-api geemap

"""# 2. Import Required Libraries"""

import ee
import geemap
import pandas as pd
import numpy as np

from datetime import datetime

"""# 3. Authenticate Google Earth Engine"""

# ==========================================
# Google Earth Engine Initialization
# ==========================================

import ee

# Authenticate (run once per new Colab session)
ee.Authenticate(force=True)

# Initialize Earth Engine with your Google Cloud Project
ee.Initialize(project="methane-hotspot-detection")

print("Google Earth Engine initialized successfully!")

import ee

print("Earth Engine Version:", ee.__version__)
print(ee.String("Earth Engine Connected Successfully!").getInfo())

"""# 4. Project Configuration

This section defines the study area, dataset information, analysis periods, and hotspot detection parameters. Keeping all project settings in one place makes the workflow easier to maintain and reproduce.
"""

# ============================================================
# PROJECT CONFIGURATION
# ============================================================

PROJECT_NAME = "Satellite-Based Methane Anomaly Detection over the Damodar Valley Coal Belt"

AUTHOR = "Dibya Jyoti Das"

# ============================================================
# STUDY AREA
# ============================================================

STUDY_AREA = "Damodar Valley Coal Belt"

COUNTRY = "India"

# ============================================================
# SATELLITE DATA
# ============================================================

SATELLITE = "Sentinel-5P"

SENSOR = "TROPOMI"

DATASET = "COPERNICUS/S5P/OFFL/L3_CH4"

# ============================================================
# BASELINE PERIOD
# Used to calculate historical methane conditions
# ============================================================

BASELINE_START = "2019-01-01"
BASELINE_END   = "2021-12-31"

# ============================================================
# ANALYSIS PERIOD
# Period where methane anomalies will be detected
# ============================================================

ANALYSIS_START = "2022-01-01"
ANALYSIS_END   = "2025-12-31"

# ============================================================
# HOTSPOT PARAMETERS
# ============================================================

SCALE = 1113           # Native Sentinel-5P resolution (~1.1 km)

ANOMALY_THRESHOLD = 2.0

print("Project Configuration Loaded Successfully")

"""# 5. Define the Study Area

The Damodar Valley Coal Belt is one of India's largest coal-producing regions, containing major coalfields such as Jharia, Bokaro, North Karanpura, Ramgarh, and Raniganj. This region is selected because coal mining activities can release methane, making it suitable for regional methane anomaly analysis.
"""

# ============================================================
# DEFINE AREA OF INTEREST (AOI)
# ============================================================

AOI_BOUNDS = [
    84.90,      # West
    23.00,      # South
    87.80,      # East
    24.60       # North
]

aoi = ee.Geometry.Rectangle(AOI_BOUNDS)

print("Area of Interest Created Successfully")

"""# 6. Visualize the Study Area

The Area of Interest (AOI) is displayed on an interactive map to verify that the selected region correctly covers the Damodar Valley Coal Belt.
"""

Map = geemap.Map()

Map.centerObject(aoi, 8)

Map.addLayer(
    aoi,
    {
        "color": "red"
    },
    "Damodar Valley Coal Belt"
)

Map

"""# 7. Load Sentinel-5P TROPOMI Methane Dataset

Sentinel-5P carries the TROPOMI instrument, which measures atmospheric trace gases including methane (CH₄). The dataset is filtered to the Damodar Valley Coal Belt and the selected analysis period.
"""

# ============================================================
# LOAD SENTINEL-5P DATASET
# ============================================================

CH4_COLLECTION = (
    ee.ImageCollection(DATASET)
    .filterDate(BASELINE_START, ANALYSIS_END)
    .filterBounds(aoi)
)

print("Sentinel-5P CH₄ Dataset Loaded Successfully")

"""# 8. Explore the Dataset

Before analysis, the dataset is inspected to determine the number of available observations and the available data bands.
"""

image_count = CH4_COLLECTION.size().getInfo()

print(f"Total Images Available : {image_count}")

first_image = CH4_COLLECTION.first()

print("Available Bands")

print(first_image.bandNames().getInfo())

"""# 9. Display the First Available Methane Observation

The first Sentinel-5P methane image is displayed to verify data availability and understand the spatial coverage of methane observations over the study area.
"""

first_image = CH4_COLLECTION.first()

vis_params = {
    "min": 1750,
    "max": 1950,
    "palette": [
        "blue",
        "cyan",
        "green",
        "yellow",
        "orange",
        "red"
    ]
}

Map = geemap.Map()

Map.centerObject(aoi,8)

Map.addLayer(
    first_image.select("CH4_column_volume_mixing_ratio_dry_air"),
    vis_params,
    "Methane"
)

Map.addLayer(
    aoi,
    {
        "color":"black"
    },
    "AOI"
)

Map

"""# 10. Data Quality Preparation

Before performing statistical analysis, the Sentinel-5P methane observations are prepared by selecting the methane band and clipping all outputs to the Damodar Valley study area. This ensures that subsequent calculations are restricted to the region of interest and reduces unnecessary processing.
"""

# ==========================================================
# Select methane band
# ==========================================================

CH4_BAND = "CH4_column_volume_mixing_ratio_dry_air"

ch4_collection = CH4_COLLECTION.select(CH4_BAND)

print("Methane band selected successfully.")

print("Total Images :", ch4_collection.size().getInfo())

"""# 11. Historical Baseline Dataset

A historical baseline is generated using observations between **2019 and 2021**.

This baseline represents the normal methane conditions in the Damodar Valley Coal Belt and will be used to identify statistically significant methane anomalies during the analysis period.
"""

# ==========================================================
# Historical Baseline
# ==========================================================

baseline = (
    ch4_collection
    .filterDate(BASELINE_START, BASELINE_END)
)

print("Baseline Images :", baseline.size().getInfo())

"""# 12. Baseline Statistics

Three statistical layers are generated from the baseline dataset:

- Mean methane concentration
- Median methane concentration
- Standard deviation

These layers form the reference against which monthly methane observations are compared.
"""

# ==========================================================
# Baseline Mean
# ==========================================================

baseline_mean = baseline.mean().clip(aoi)

# ==========================================================
# Baseline Median
# ==========================================================

baseline_median = baseline.median().clip(aoi)

# ==========================================================
# Baseline Standard Deviation
# ==========================================================

baseline_std = (
    baseline
    .reduce(ee.Reducer.stdDev())
    .clip(aoi)
)

print("Baseline statistics created successfully.")

"""# 13. Visualize Historical Mean Methane"""

mean_vis = {
    "min": 1885,
    "max": 1925,
    "palette": [
        "#313695",
        "#4575b4",
        "#74add1",
        "#abd9e9",
        "#ffffbf",
        "#fee090",
        "#fdae61",
        "#f46d43",
        "#d73027",
        "#a50026"
    ]
}

Map = geemap.Map()

Map.centerObject(aoi,8)

Map.addLayer(
    baseline_mean,
    mean_vis,
    "Baseline Mean"
)

Map.addLayer(
    aoi,
    {
        "color":"black"
    },
    "Study Area"
)

Map

"""# 14. Baseline Standard Deviation"""

std_vis = {
    "min":0,
    "max":30,
    "palette":[
        "white",
        "yellow",
        "orange",
        "red"
    ]
}

Map = geemap.Map()

Map.centerObject(aoi,8)

Map.addLayer(
    baseline_std,
    std_vis,
    "Baseline Standard Deviation"
)

Map.addLayer(
    aoi,
    {
        "color":"black"
    },
    "Study Area"
)

Map

"""# 15. Baseline Summary Statistics"""

# ==========================================================
# Baseline Summary Statistics
# ==========================================================

stats = baseline_mean.reduceRegion(
    reducer=ee.Reducer.minMax()
            .combine(
                reducer2=ee.Reducer.mean(),
                sharedInputs=True
            )
            .combine(
                reducer2=ee.Reducer.stdDev(),
                sharedInputs=True
            ),
    geometry=aoi,
    scale=SCALE,
    maxPixels=1e13
)

print("========== BASELINE STATISTICS ==========")

print(stats.getInfo())

"""# 16. Monthly Composite Generation

Monthly methane composites are generated for the analysis period (2022–2025).

Each composite represents the median methane concentration for one calendar month.
"""

# ============================================================
# CREATE MONTHLY DATE LIST
# ============================================================

from datetime import datetime

months = []

for year in range(2022,2026):

    for month in range(1,13):

        months.append(
            ee.Date.fromYMD(year,month,1)
        )

print("Months Created :",len(months))

"""# 17. Build Monthly Methane Collection"""

monthly_images=[]

for start in months:

    end=start.advance(1,"month")

    img=(
        ch4_collection
        .filterDate(start,end)
        .median()
        .clip(aoi)
        .set("system:time_start",start.millis())
    )

    monthly_images.append(img)

monthly_collection=ee.ImageCollection(monthly_images)

print("Monthly Collection Created")

print(monthly_collection.size().getInfo())

"""# 18. Calculate Monthly Methane Anomalies

To identify abnormal methane concentrations, each monthly methane composite is compared with the historical baseline (2019–2021).

The anomaly is calculated as:

Monthly Methane − Historical Mean Methane

Positive values indicate methane concentrations higher than the historical average, while negative values indicate lower-than-average concentrations.
"""

# ==========================================================
# Calculate Monthly Methane Anomaly
# ==========================================================

def calculate_anomaly(image):

    anomaly = image.subtract(baseline_mean)

    return (
        anomaly.rename("CH4_Anomaly")
        .copyProperties(image, image.propertyNames())
    )

anomaly_collection = monthly_collection.map(calculate_anomaly)

print("Monthly anomaly collection created successfully.")

print("Number of anomaly images:", anomaly_collection.size().getInfo())

"""# 19. Visualize Monthly Methane Anomaly

The first monthly methane anomaly image is displayed to verify that anomaly calculations have been performed correctly.

Blue colors represent methane concentrations below the historical baseline.

Red colors represent methane concentrations above the historical baseline.
"""

# ==========================================================
# Display First Monthly Anomaly
# ==========================================================

first_anomaly = anomaly_collection.first()

anomaly_vis = {
    "min": -50,
    "max": 50,
    "palette": [
        "#313695",
        "#74add1",
        "#ffffff",
        "#fdae61",
        "#d73027"
    ]
}

Map = geemap.Map()

Map.centerObject(aoi, 8)

Map.addLayer(
    first_anomaly.clip(aoi),
    anomaly_vis,
    "Monthly Methane Anomaly"
)

Map.addLayer(
    aoi,
    {"color": "black"},
    "Study Area"
)

Map

"""# 20. Calculate Monthly Z-score

To determine whether methane anomalies are statistically significant, a z-score is calculated for each monthly composite.

The z-score is computed as:

Z = (Monthly Methane − Historical Mean) / Historical Standard Deviation

Higher positive values indicate methane concentrations that are unusually high compared to historical conditions.
"""

# ==========================================================
# Remove Zero Standard Deviation Pixels
# ==========================================================

safe_std = baseline_std.where(
    baseline_std.eq(0),
    1
)

# ==========================================================
# Calculate Monthly Z-score
# ==========================================================

def calculate_zscore(image):

    z = image.subtract(baseline_mean).divide(safe_std)

    return (
        z.rename("Z_Score")
        .copyProperties(image, image.propertyNames())
    )

zscore_collection = monthly_collection.map(calculate_zscore)

print("Monthly Z-score collection created successfully.")

print("Total Images:", zscore_collection.size().getInfo())

"""# 21. Visualize Monthly Z-score

The z-score map highlights statistically significant methane enhancements.

Values near zero represent normal methane conditions.

Positive values indicate methane concentrations above the historical baseline.

Negative values indicate methane concentrations below the historical baseline.
"""

z_vis = {
    "min": -2,
    "max": 5,
    "palette": [
        "#313695",
        "#74add1",
        "#ffffbf",
        "#fdae61",
        "#d73027"
    ]
}

first_z = zscore_collection.first()

Map = geemap.Map()

Map.centerObject(aoi, 8)

Map.addLayer(
    first_z.clip(aoi),
    z_vis,
    "Monthly Z-score"
)

Map.addLayer(
    aoi,
    {"color": "black"},
    "Study Area"
)

Map

"""# 22. Detect Methane Hotspots

Pixels with a z-score greater than or equal to the predefined threshold are classified as methane hotspots.

For this project, a threshold of **2 standard deviations above the historical baseline** is used.
"""

# ==========================================================
# Detect Methane Hotspots
# ==========================================================

def detect_hotspots(image):

    hotspot = image.gte(ANOMALY_THRESHOLD)

    return (
        hotspot.rename("Hotspot")
        .copyProperties(image, image.propertyNames())
    )

hotspot_collection = zscore_collection.map(detect_hotspots)

print("Hotspot collection created successfully.")

"""# 23. Display the First Hotspot Map

The first monthly hotspot map displays pixels where methane concentrations exceed two standard deviations above the historical baseline.
"""

# ==========================================================
# Display Monthly Methane Hotspot Map
# ==========================================================

# Use the hotspot image with the highest number of hotspot pixels
display_hotspot = hotspot_collection.sort("system:time_start", False).first()

hotspot_vis = {
    "min": 0,
    "max": 1,
    "palette": [
        "#000000",
        "#ff0000"
    ]
}

Map = geemap.Map()

Map.centerObject(aoi, 8)

# Satellite Basemap
Map.add_basemap("SATELLITE")

# Display Hotspots
Map.addLayer(
    display_hotspot.selfMask().clip(aoi),
    hotspot_vis,
    "Methane Hotspots"
)

# Study Area Boundary
Map.addLayer(
    aoi,
    {
        "color": "yellow"
    },
    "Study Area"
)

Map.addLayerControl()

Map

"""# 24. Persistent Methane Hotspot Analysis

Monthly hotspot maps indicate methane anomalies for individual months. However, isolated monthly hotspots may result from transient atmospheric conditions or retrieval variability.

To identify more reliable methane emission sources, a persistence analysis is performed by counting the number of months during which each pixel exceeds the hotspot threshold.

Pixels detected repeatedly are considered persistent methane hotspots.
"""

# ==========================================================
# Calculate Hotspot Persistence
# ==========================================================

persistence = hotspot_collection.sum().clip(aoi)

print("Persistent Hotspot Image Created Successfully")

"""# 25. Visualize Persistent Hotspots

The persistence map represents the number of months during which each pixel was classified as a methane hotspot.

Higher values indicate locations where methane anomalies occurred repeatedly throughout the analysis period.
"""

persistence_vis = {
    "min": 0,
    "max": 24,
    "palette": [
        "#ffffcc",
        "#c2e699",
        "#78c679",
        "#31a354",
        "#006837"
    ]
}

Map = geemap.Map()

Map.centerObject(aoi,8)

Map.addLayer(
    persistence.selfMask(),
    persistence_vis,
    "Persistent Hotspots"
)

Map.addLayer(
    aoi,
    {
        "color":"black"
    },
    "Study Area"
)

Map

"""# 26. Persistent Hotspot Statistics

Basic statistics are calculated to summarize hotspot persistence across the study area.
"""

stats = persistence.reduceRegion(
    reducer=ee.Reducer.max()
            .combine(
                reducer2=ee.Reducer.mean(),
                sharedInputs=True
            ),
    geometry=aoi,
    scale=SCALE,
    maxPixels=1e13
)

print(stats.getInfo())

"""# 27. Extract Persistent Hotspots

Pixels detected during multiple months are extracted for further analysis.

For this study, hotspots occurring during at least **6 months** are considered persistent.
"""

PERSISTENCE_THRESHOLD = 8

persistent_hotspots = persistence.gte(PERSISTENCE_THRESHOLD)

"""# 28. Display Persistent Hotspots"""

Map = geemap.Map()

Map.centerObject(aoi,8)

Map.addLayer(
    persistent_hotspots.selfMask(),
    {
        "palette":["red"]
    },
    "Persistent Hotspots"
)

Map.addLayer(
    aoi,
    {
        "color":"white"
    },
    "AOI"
)

Map

"""# 29. Convert Persistent Hotspots into Vector Features

Persistent hotspot pixels are converted into vector polygons to enable area calculation and coordinate extraction.
"""

vectors = persistent_hotspots.selfMask().reduceToVectors(

    geometry=aoi,

    scale=SCALE,

    geometryType="polygon",

    eightConnected=True,

    maxPixels=1e13
)

print("Vector Features Created")

"""# 30. Number of Persistent Hotspots"""

print("Number of Persistent Hotspots :")

print(vectors.size().getInfo())

"""# 31. Display Persistent Hotspot Polygons"""

Map = geemap.Map()

Map.centerObject(aoi,8)

Map.addLayer(
    persistence,
    persistence_vis,
    "Persistence"
)

Map.addLayer(
    vectors,
    {
        "color":"black"
    },
    "Hotspot Polygons"
)

Map

"""# 32. Calculate Hotspot Centroids

The centroid of each hotspot polygon is calculated for mapping and reporting purposes.
"""

centroids = vectors.map(
    lambda feature: ee.Feature(
        feature.geometry().centroid(
            ee.ErrorMargin(1)
        )
    )
)

print("Centroids Created Successfully")

"""# 33. Display Hotspot Centroids"""

Map = geemap.Map()

Map.centerObject(aoi,8)

Map.addLayer(
    persistence,
    persistence_vis,
    "Persistence"
)

Map.addLayer(
    centroids,
    {
        "color":"blue"
    },
    "Hotspot Centroids"
)

Map

"""# 34. Calculate Hotspot Area

Each persistent hotspot polygon is assigned an area in square kilometres.

This provides a quantitative estimate of the spatial extent of each methane hotspot.
"""

def add_area(feature):

    area = (
        feature.geometry()
        .area(
            ee.ErrorMargin(1)
        )
        .divide(1e6)
    )

    return feature.set(
        "Area_km2",
        area
    )

hotspots_area = vectors.map(add_area)

print("Area Calculated Successfully")

"""# 35. Calculate Hotspot Centroid Coordinates

Latitude and longitude coordinates are calculated for each hotspot centroid.
"""

def add_coordinates(feature):

    centroid = feature.geometry().centroid(
        ee.ErrorMargin(1)
    )

    coordinates = centroid.coordinates()

    return (
        feature
        .set(
            "Longitude",
            coordinates.get(0)
        )
        .set(
            "Latitude",
            coordinates.get(1)
        )
    )

hotspots_coordinates = hotspots_area.map(add_coordinates)

print("Coordinates Added Successfully")

"""# 36. Rank Persistent Hotspots

Hotspots are ranked according to their spatial extent.

Larger hotspot polygons are assigned higher priority for further investigation.
"""

# ==========================================================
# Sort Hotspots by Area
# ==========================================================

def add_hotspot_score(feature):

    area = ee.Number(
        feature.get("Area_km2")
    )

    score = area

    return feature.set(
        "Hotspot_Score",
        score
    )

ranked_hotspots = (
    hotspots_coordinates
    .map(add_hotspot_score)
    .sort(
        "Hotspot_Score",
        False
    )
)

print("Hotspots Ranked Successfully")

"""# 37. Display Top 10 Hotspots"""

# ==========================================================
# Calculate Area of Each Hotspot (Corrected)
# ==========================================================

def add_area(feature):

    area_km2 = (
        feature.geometry()
        .area(ee.ErrorMargin(1))
        .divide(1e6)
    )

    return feature.set("Area_km2", area_km2)

hotspots_area = vectors.map(add_area)

print("Area Calculated Successfully")

"""# 38. Export Hotspots as CSV"""

# ==========================================================
# Export CSV
# ==========================================================

task = ee.batch.Export.table.toDrive(

    collection=ranked_hotspots,

    description="Damodar_Valley_CH4_Persistent_Hotspots_2022_2025",

    folder="Methane_Project",

    fileFormat="CSV"

)

task.start()

print("CSV Export Started")

"""# 39. Export Hotspots as GeoJSON"""

task = ee.batch.Export.table.toDrive(

    collection=ranked_hotspots,

    description="Damodar_Valley_CH4_Hotspots_GeoJSON_2022_2025",

    folder="Methane_Project",

    fileFormat="GeoJSON"

)

task.start()

print("GeoJSON Export Started")

"""# 40. Export Persistent Hotspot Raster"""

task = ee.batch.Export.image.toDrive(

    image=persistence,

    description="Damodar_Valley_CH4_Persistence_Raster_2022_2025",

    folder="Methane_Project",

    region=aoi,

    scale=SCALE,

    maxPixels=1e13

)

task.start()

print("Raster Export Started")

"""# 41. Interactive Baseline Map"""

# ==========================================================
# Interactive Historical Baseline Map
# ==========================================================

baseline_map = geemap.Map()

# Center the map over the study area
baseline_map.centerObject(aoi, 8)

# Add Historical Mean Methane Layer
baseline_map.addLayer(
    baseline_mean.clip(aoi),
    mean_vis,
    "Historical Mean Methane"
)

# Add Persistent Hotspot Polygons
baseline_map.addLayer(
    vectors,
    {
        "color": "black"
    },
    "Persistent Hotspot Polygons"
)

# Add Study Area Boundary
baseline_map.addLayer(
    aoi,
    {
        "color": "red"
    },
    "Study Area Boundary"
)

# Add Layer Control
baseline_map.addLayerControl()

# Display Map
baseline_map

"""# 42. Save Interactive Baseline Map"""

baseline_map.to_html(
    "baseline_map.html"
)

print("HTML Saved")

"""# 43. Interactive Persistence Map"""

# ==========================================================
# Interactive Persistent Methane Hotspot Map
# ==========================================================

persist_map = geemap.Map()

# Center the map over the study area
persist_map.centerObject(aoi, 8)

# Add Persistent Hotspot Frequency Raster
persist_map.addLayer(
    persistence.clip(aoi),
    persistence_vis,
    "Persistent Hotspot Frequency"
)

# Add Persistent Hotspot Polygons
persist_map.addLayer(
    vectors,
    {
        "color": "black"
    },
    "Persistent Hotspot Polygons"
)

# Add Study Area Boundary
persist_map.addLayer(
    aoi,
    {
        "color": "red"
    },
    "Study Area Boundary"
)

# Add Layer Control
persist_map.addLayerControl()

# Display Interactive Map
persist_map

"""# 44. Save Persistence Map"""

persist_map.to_html(
    "persistent_hotspots.html"
)

print("Persistence HTML Saved")

"""# 45. Project Summary"""

print("=" * 60)

print(PROJECT_NAME)

print("=" * 60)

print(f"Study Area             : {STUDY_AREA}")

print(f"Country                : {COUNTRY}")

print(f"Satellite              : {SATELLITE}")

print(f"Sensor                 : {SENSOR}")

print(f"Baseline Period        : {BASELINE_START} to {BASELINE_END}")

print(f"Analysis Period        : {ANALYSIS_START} to {ANALYSIS_END}")

print(f"Monthly Images         : {monthly_collection.size().getInfo()}")

print(f"Persistent Hotspots    : {vectors.size().getInfo()}")

print(f"Persistence Threshold  : {PERSISTENCE_THRESHOLD} months")

print("=" * 60)

"""# 45A. Execution Time

The total execution time of the workflow is calculated to provide an estimate of the computational efficiency of the methane hotspot detection process. This information is useful for evaluating workflow performance and documenting computational requirements.
"""

import time

start_time = time.time()

# ==========================================================
# Workflow Execution Summary
# ==========================================================

end_time = time.time()

execution_time = end_time - start_time

print("=" * 70)
print("WORKFLOW EXECUTION SUMMARY")
print("=" * 70)

print(f"Notebook Execution Time : {execution_time:.2f} seconds")
print("Processing Platform     : Google Earth Engine Cloud")
print("Computation Model       : Server-side distributed processing")

print("=" * 70)

"""# 46. Project Completed"""

print("""
Satellite-Based Methane Anomaly Detection
Completed Successfully.

Outputs Generated

✓ Baseline Map

✓ Monthly Methane Maps

✓ Monthly Z-score Maps

✓ Persistent Hotspots

✓ Vector Hotspots

✓ CSV Export

✓ GeoJSON Export

✓ Interactive HTML Maps

✓ Google Earth Engine Workflow

✓ Ready for GitHub
""")